# YouDu IM MCP Server 测试配置文件
# 此文件专门用于测试，不影响生产环境的 config.yaml

youdu:
  addr: "http://mock.test"  # 将被测试代码动态覆盖为 Mock Server URL
  buin: 123456789
  app_id: "test_app_id"
  aes_key: "dGVzdF9hZXNfa2V5XzMyX2NoYXJhY3RlcnNfbG9uZyE="

# 权限配置 - 与 testdata/test_cases.go 中的权限设置一致
permission:
  # 启用权限检查
  enabled: true

  # 不允许所有操作（严格模式）
  allow_all: false

  # 资源权限配置
  resources:
    # 用户权限
    user:
      create: false   # 禁止创建用户
      read: true      # 允许读取用户信息
      update: false   # 禁止更新用户
      delete: false   # 禁止删除用户

    # 消息权限
    message:
      create: true    # 允许发送消息
      read: true      # 允许读取消息
      update: false   # 禁止更新消息
      delete: false   # 禁止删除消息

    # 部门权限
    dept:
      create: false   # 禁止创建部门
      read: true      # 允许读取部门信息
      update: false   # 禁止更新部门
      delete: false   # 禁止删除部门

    # 群组权限
    group:
      create: false   # 禁止创建群组
      read: true      # 允许读取群组信息
      update: false   # 禁止更新群组
      delete: false   # 禁止删除群组

    # 会话权限
    session:
      create: false   # 禁止创建会话
      read: true      # 允许读取会话信息
      update: false   # 禁止更新会话
      delete: false   # 禁止删除会话
