# 有度即时通讯配置
youdu:
  # 有度服务器地址
  addr: "http://your-youdu-server:7080"
  # 企业总机号
  buin: 123456789
  # 应用ID
  app_id: "your-app-id"
  # AES加密密钥
  aes_key: "your-aes-key"

# 权限配置
permission:
  # 是否启用权限检查（true=启用，false=禁用）
  enabled: true

  # 是否允许所有操作（仅用于开发/调试，生产环境应设为 false）
  allow_all: false

  # 资源权限配置
  resources:
    # 部门权限
    dept:
      create: false   # 禁止创建部门
      read: true     # 允许读取部门信息
      update: false   # 禁止更新部门
      delete: false  # 禁止删除部门

    # 用户权限
    user:
      create: false   # 禁止创建用户
      read: true     # 允许读取用户信息
      update: false   # 禁止更新用户
      delete: false  # 禁止删除用户

    # 群组权限
    group:
      create: true   # 允许创建群组
      read: true     # 允许读取群组信息
      update: true   # 允许更新群组
      delete: false  # 禁止删除群组

    # 会话权限
    session:
      create: true   # 允许创建会话
      read: true     # 允许读取会话信息
      update: true   # 允许更新会话
      delete: false  # 禁止删除会话

    # 消息权限
    message:
      create: true   # 允许发送消息
      read: true     # 允许读取消息
      update: false  # 禁止更新消息（消息一般不可修改）
      delete: false  # 禁止删除消息

# Token 认证配置
token:
  # 是否启用 token 认证（true=启用，false=禁用）
  enabled: false

  # 预定义的 token 列表
  # 建议使用 CLI 命令生成 token: youdu-cli token generate
  tokens:
    # - id: "abc123"
    #   value: "your-token-value-here"
    #   description: "API access token for service A"
    #   created_at: "2024-01-01T00:00:00Z"
    # - id: "def456"
    #   value: "another-token-value"
    #   description: "API access token for service B"
    #   created_at: "2024-01-01T00:00:00Z"
